### ISSUE TITLE
용어정리

### ISSUE THREAD

**Issue by fora22** [fora22/TranslateGKO#1]
# 용어정리
번역에 쓰일 용어 정리하길 바랍니다.
Interpreter
-> [1] 인터프리터
-> [2] Interpreter

**Comment by GKO95** [comment]
2020.04.28:1341 기준 용어정리 업데이트입니다. (2020.04.28:1344 용어 +1추가)

## 용어등록
다음은 새로 등록된 용어 목록입니다.
### PYTHON: BASIC
* high-level programming language<br/>: 고급 프로그래밍 언어
* variable<br/>: 변수
* function<br/>: 함수
* syntax<br/>: 구문
* keyword<br/>: 키워드
* statement<br/>: 문

### PYTHON: ITERABLE OBJECT
* iterable object<br/>: 가(可)반복 객체
* iterator<br/>: 반복자

### PYTHON: FUNCTIONAL PROGRAMMING
* procedural programming<br/>: 절차적 프로그래밍
* functional programming<br/>: 함수형 프로그래밍
* object-oriented programming (OOP)<br/>: 객체지향 프로그래밍
* parameter<br/>: 매개변수
* argument<br/>: (전달)인자
* pure function<br/>: 순수 함수
* higher-order function<br/>: 고차 함수
* anonymous function<br/>: 익명 함수
* lambda expression<br/>: 람다 표현식
* recursive function<br/>: 재귀 함수

## 용어정정
다음은 기존에 등록된 용어 정정 목록입니다.
~~해당 없음~~

**Comment by fora22** [comment]
> 2020.04.28:1341 기준 용어정리 업데이트입니다. (2020.04.28:1344 용어 +1추가)
> 
> ## 용어등록
> 다음은 새로 등록된 용어 목록입니다.
> 
> ### PYTHON: BASIC
> * high-level programming language: 고급 프로그래밍 언어
> * variable: 변수
> * function: 함수
> * syntax: 구문
> * keyword: 키워드
> * statement: 문
> 
> ### PYTHON: ITERABLE OBJECT
> * iterable object: 가(可)반복 객체
> * iterator: 반복자
> 
> ### PYTHON: FUNCTIONAL PROGRAMMING
> * procedural programming: 절차적 프로그래밍
> * functional programming: 함수형 프로그래밍
> * object-oriented programming (OOP): 객체지향 프로그래밍
> * parameter: 매개변수
> * argument: (전달)인자
> * pure function: 순수 함수
> * higher-order function: 고차 함수
> * anonymous function: 익명 함수
> * lambda expression: 람다 표현식
> * recursive function: 재귀 함수
> 
> ## 용어정정
> 다음은 기존에 등록된 용어 정정 목록입니다.
> ~해당 없음~

1. syntax : 구문
> **syntax : 구문** 보다는
  **syntax : 문법** 이 보다 적절한 번역이라고 생각합니다.

2. iterable object: 가(可)반복 객체
> - 가 반복 객체는 뜻이 맞으나 보통 사용하지 않는 용어입니다. 
'반복 가능한 객체' 정도가 괜찮을 것 같습니다.
> - 읽는 사람이 하나의 용어임을 알 수 있게 '  '  작은 따옴표를 사용하는 것이 좋을 것 같습니다.

**Comment by GKO95** [comment]
1. 위키백과에서 syntax를 "구문"이라고 하며, 문법에 대한 정의가 따로 있는 것으로 보인다.
*URL: https://ko.wikipedia.org/wiki/구문_(프로그래밍_언어)*

2. 이에 대한 내용은 issue #2 에서 상의하도록 한다.

**Comment by fora22** [comment]
> 1. 위키백과에서 syntax를 "구문"이라고 하며, 문법에 대한 정의가 따로 있는 것으로 보인다.
>    _URL: [https://ko.wikipedia.org/wiki/구문_(프로그래밍_언어)](https://ko.wikipedia.org/wiki/%EA%B5%AC%EB%AC%B8_(%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%B0%8D_%EC%96%B8%EC%96%B4))_

1. 문법은 Grammer라고 하네요. 알겠습니다~

**Comment by GKO95** [comment]
2020.04.30:1719 기준 용어정리 업데이트입니다.
*URL: [README.md](https://github.com/fora22/TranslateGKO/blob/master/README.md)*
