### ISSUE TITLE
영어를 다 한글로 번역하는게 좋을까요?

### ISSUE THREAD

**Issue by fora22** [fora22/TranslateGKO#2]
영어 단어중에 한글로 번역하면 의역이 힘든 경우가 있는데 이때도 한글로 번역하는게 좋을까요?

**Comment by GKO95** [comment]
번역에는 정답이 없으며, 가장 좋은 것은 널리 통용되는 용어를 사용하는 게 올바른 방법이다. 그러하지 않은 용어가 있다면 직역이 아니더라도 독자가 납득할 수 있는 가장 적합한 용어를 택하여 사용한다.

기술적인 내용은 영문을 그대로 사용하는 경우가 흔하다. 그러나 한글로 번역하려는 이유는 해당 객체가 무엇을 위해 사용되는지 확실하게 이해시키기 위해서이다. 대표적인 예로 iterable는 영문 그대로 쓰이는 경우가 많은데, iterable이란 단어가 무슨 뜻인지 알고 있으면 이해하는데 큰 도움이 된다. 그러한 이유로 최소한 용어 번역을 제공하려는 것이다.

하지만 어떠한 용어를 사용할 것인지는 번역자들간의 일치된 의견이 필요하다. 번역이 애매모호한 용어가 있으면 이슈에 올려 논의하도록 하자.

**Comment by fora22** [comment]
iterable Object는 '반복 가능한 객체' 정도가 괜찮을 것 같은데 어떠세요?

**Comment by GKO95** [comment]
"반복 가능한 객체"라고 하자. 어차피 가반복 객체란 용어 자체도 알아듣기 힘들어.
