### ISSUE TITLE
문장 수정 요청

### ISSUE THREAD

**Issue by fora22** [fora22/TranslateGKO#3]
# 문장 수정 요청

### Interprter

>Programming language such as C/C++ uses compiler that translates a source code (written in English) to a computer language (such as binary language) computer can understand for execution. **However, interpreter allows computer to execute the program directly from a source code without translation.**

제가 여기서 **그러나, 인터프리터는 컴퓨터가 번역 없이 소스코드에서 직접 프로그램을 실행할 수 있도록 한다.** 라고 번역을 했는데, 문장이 좀 잘못된 것 같습니다.
인터프리터도 일단은 기계어로 번역을 할텐데 *without translation* 은 잘못된 것 아닌가요?

**Comment by GKO95** [comment]
인터프리터에 대한 정의는 다음과 같다:
> In computer science, an interpreter is a computer program that directly executes instructions written in a programming or scripting language, without requiring them previously to have been compiled into a machine language program.

해석하면, "프로그래밍 혹은 스크립트 언어에서 바로 명령어를 실행하며 기계어로 컴파일 단계가 필요없다."라고 적혀있다. 그러므로 컴퓨터 언어로 번역하지 않는 것은 맞는 말이다.

**Comment by fora22** [comment]
음 제가 잘못 적었네요 기계어 번역이 아니라 중간 코드로 번역할텐데, 번역이 없다는 표현은 잘못된거 아닐까 해서용

**Comment by GKO95** [comment]
본 내용은 인터프리터 그 자체에 대한 내용이며, 개념상 컴파일러 언어와 인터프리터 언어의 차이를 알려주기 위해 작성된 글이야. 저번에 알려주었듯이 CPython에서 스크립트를 bytecode로 우선 컴파일하고 인터프리터가 읽는 것은 맞지만 인터프리터가 bytecode를 직접 읽어서 프로그램을 실행하는 것은 변함이 없어.

**Comment by fora22** [comment]
흠 알겠습니당
